- name: "ANNOTATE"
  color: "02FFAD"
  description: "[Product] Relating to the ANNOTATE platform."
- name: "AUDIT"
  color: "02FFAD"
  description: "[Product] Relating to the AUDIT platform."
  - name: "CURATE"
  color: "02FFAD"
  description: "[Product] Relating to the CURATE platform."
  - name: "DOCUMENT"
  color: "02FFAD"
  description: "[Product] Relating to the DOCUMENT platform."
  - name: "MANAGE"
  color: "02FFAD"
  description: "[Product] Relating to the MANAGE platform."
  - name: "REGISTER"
  color: "02FFAD"
  description: "[Product] Relating to the REGISTER platform."
  - name: "STYLE"
  color: "02FFAD"
  description: "[Product] Relating to the STYLE platform."
  - name: "UPLOAD"
  color: "02FFAD"
  description: "[Product] Relating to the UPLOAD platform."
